### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by barrredemption7** [leonv024/WildixEnum#1]
whose profile and name will be showing when chatting with any user?

**Comment by leonv024** [comment]
On the IRC, your own, on the C&C, none. Just "Anonymous".

The site chat is too bugged, so it's better to use the IRC. You can enter your RAASNet username and check "I have a password" and enter your password to login to the IRC.

However, if you wish to remain anonymous, you can click connect with the given username, you'll be displayed as "anonymous".

Does this answer your question?

**Comment by leonv024** [comment]
The given name. You can give any name you wish without a password.
